language: python

sudo: false

cache: pip

python:
  - 2.7
  - 3.5

install:
  - pip install pip setuptools --upgrade
  - pip install -e .\[all\]

script:
  - pytest tests --cov tinymr --cov-report term-missing

after_success:
  - coveralls
